[package]
name = "password-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
copypasta = "0.10.0"
rand = "0.8.5"
rpassword = "7.3.1"
serde = { version = "1.0.195", features = ["derive"] }
